nohup uv run python object-detection-detr/train.py \
    --cls_thr 0.1 \
    --model_name ustc-community/dfine-medium-coco \
    --num_class 3 \
    --label_names "class_A" "class_B" "class_C" \
    --validation_csv "dataset/full_valid.json" \
    --image_folder "." \
    --training_csv "dataset/full_train.json" \
    --output_dir logs \
    --run_name dfine-medium-coco \
    --auto_find_batch_size \
    --per_device_train_batch_size 24 \
    --per_device_eval_batch_size 24 \
    --num_train_epochs 200 \
    --do_eval \
    --do_train \
    --fp16 \
    --learning_rate 1e-4 \
    --weight_decay 1e-5 \
    --save_total_limit 2 \
    --remove_unused_columns false \
    --push_to_hub false \
    --eval_strategy epoch \
    --save_strategy epoch \
    --logging_steps 0.5 \
    --report_to wandb \
    --optim adamw_torch \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.05 \
    --data_seed 41 \
    --save_safetensors \
    --save_only_model \
    --metric_for_best_model loss \
    --load_best_model_at_end \
    --overwrite_output_dir \
    --dataloader_num_workers 8 \
    --gradient_accumulation_steps 1 \
    &> nohup.out &
